### ISSUE TITLE
When I remove Advanced Search Highlight, but the page still has search bar

### ISSUE THREAD

**Issue by gitzaai** [clarkwinkelmann/flarum-ext-advanced-search-highlight#1]
When I remove Advanced Search Highlight, but the page still has search bar.

![Snipaste_2023-06-30_22-29-39.jpg](https://cdnjson.com/images/2023/06/30/Snipaste_2023-06-30_22-29-39.jpg)

**Comment by clarkwinkelmann** [comment]
This extension does not add any additional search bar, it only modifies the user content formatting inside discussion excerpts and the post stream.

I don't know which extension adds a search bar at the top of the discussion list, but I suspect it shouldn't be difficult to find by reading your list of extensions. Maybe it's an extension that does just that, or maybe it's part of your theme.

If you need further help, I suggest you ask over on the Flarum community or Discord.
